[tools]
antigravity-cli = "latest"
cloudflared = "latest"
codex = "latest"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
herdr = "latest"
lazygit = "latest"
"llama.cpp" = { version = "latest", version_prefix = "b" }
make = "latest"
marp-cli = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
ripgrep = "latest"
rust = "stable"
starship = "latest"
swift = "latest"
tmux = "latest"
typst = "latest"
uv = "latest"
yazi = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zig = "latest"
zoxide = "latest"

[shell_alias]
miseup="mise self-update -y"
vi="nvim"
llama-is="llama-server --fim-qwen-1.5b-default --port 8080 --host 0.0.0.0"
ll="ls -la"
